### ISSUE TITLE
Specs description different from what it's actually looking for

### ISSUE THREAD

**Issue by RachelSa** [learn-co-curriculum/emoticon-translator#6]
The specs for get_japanese_emoticon seem to be looking for a string of the Japanese emoticon as the return (such as "(＾ｖ＾)"). However, I could only get tests passing when I returned the word (such as :happy). 

I don't know how this happens, since the specs indicate the emoticon as the return:
it "returns the Japanese equivalent of an English grinning" do
    expect(get_japanese_emoticon("./lib/emoticons.yml", "=D")).to eq("(￣ー￣)")
  end

But my tests all failed when I returned the emojis.

**Comment by maxwellbenton** [comment]
Hi @RachelSa,

Thank you for opening this issue and providing this feedback. Unfortunately, I was unable to replicate the issue you had here. However, we've recently updated this lesson, including making the tests more flexible.

Hope you are well my friend!
