### ISSUE TITLE
Test not working with certain hash syntax

### ISSUE THREAD

**Issue by kodyclemens** [learn-co-curriculum/emoticon-translator#7]
The test will not pass if you define your hash like this in the load_library method:

`a_hash = { "get_meaning": {}, "get_emoticon": {} }`

You must define it like this:
`a_hash = { "get_meaning" => {}, "get_emoticon" => {} }`

I recommend changing the tests so that both work. If I am missing something important about the two syntax styles, which requires one over the other for this lab, please reply.

**Comment by maxwellbenton** [comment]
Hi @kodyclemens,

Thank you for spotting this and providing feedback. We've updated the tests in this lab to handle either syntax and included a message about what is happening (Ruby is converting string keys to symbols if you use the `:` syntax, but does not do the same with `=>`). We believe this issue should now be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
